###############################################################
#
#  This configures the robot to work with MoveIt Pro
#
###############################################################

# Extend the basic Kinova MuJoCo configuration
based_on_package: kinova_gen3_mujoco_config

# Baseline hardware configuration parameters for MoveIt Pro.
# [Required]
hardware:
  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    urdf:
      package: "picknik_kinova_satellite_sim"
      path: "description/picknik_kinova_satellite_sim.xacro"
    # Specify any additional parameters required for the URDF.
    # Many of these are specific to the UR descriptions packages, and can be customized as needed.
    # [Optional]
    urdf_params:
      - arm: "gen3"
      - dof: "7"
      - vision: "false"
      - gripper: "robotiq_2f_85"
      - use_fake_hardware: "%>> hardware.simulated"
      - fake_sensor_commands: "false"
      - external_camera: "true"
      - wrist_realsense: "true"
      - use_internal_bus_gripper_comm: "false"
      - mujoco_model: "description/mujoco/scene.xml"
      - mujoco_viewer: "true"

# Configuration for loading behaviors and objectives.
# [Required]
objectives:
  # List of plugins for loading custom behaviors.
  # [Required]
  behavior_loader_plugins:
    # This plugin will load the core MoveIt Pro Behaviors.
    # Add additional plugin loaders as needed.
    core:
      - "moveit_studio::behaviors::CoreBehaviorsLoader"
      - "moveit_studio::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_studio::behaviors::ServoBehaviorsLoader"
      - "moveit_studio::behaviors::VisionBehaviorsLoader"
  # Specify source folder for objectives
  # [Required]
  objective_library_paths:
    core:
      package_name: "picknik_kinova_satellite_sim"
      relative_path: "objectives"
  # Specify the location of the saved waypoints file.
  # [Required]
  waypoints_file:
    package_name: "picknik_kinova_satellite_sim"
    relative_path: "waypoints/waypoints.yaml"
